server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
          autoregister_listeners: true

jwt:
  secret: your_secret_key
  expiration: 3600000

scheduled:
  shutdown-time: 2024-12-31T23:59:59